name: Update bein.m3u hourly

on:
  schedule:
    - cron: "0 * * * *"   # كل ساعة بالضبط (UTC)
  workflow_dispatch:      # تشغيل يدوي عند الحاجة

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # نحتاج نكتب/نكمّت التغييرات
    env:
      TZ: Asia/Baghdad
      WATCH_URL: "https://dlhd.dad/watch.php?id=91"
      BUTTON_TITLE: "PLAYER 6"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper & update file
        run: |
          python src/update_bein.py

      - name: Commit & push if changed
        run: |
          if git diff --quiet; then
            echo "No changes."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add bein.m3u
            git commit -m "chore: auto-update bein sports 1 m3u8 (hourly)"
            git push
          fi
