name: Pull MATCH! Football (every 5 min)

on:
  schedule:
    - cron: "*/5 * * * *"   # كل 5 دقائق
  workflow_dispatch:        # تشغيل يدوي

permissions:
  contents: write           # حتى يقدر يحدّث الملف عبر GitHub API

concurrency:
  group: pull-match-football
  cancel-in-progress: true

jobs:
  update-generalsports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run updater script (uses built-in GITHUB_TOKEN)
        env:
          # توكن الأكشن المدمج (يكفي للتحديث عبر Contents API)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # (اختياري) تقدر تغيّر القيم التالية، لكن الافتراضات مضبوطة:
          # SOURCE_URL: "https://raw.githubusercontent.com/DisabledAbel/daddylivehd-m3u/f582ae100c91adf8c8db905a8f97beb42f369a0b/daddylive-events.m3u8"
          # DEST_RAW_URL: "https://raw.githubusercontent.com/a7shk1/m3u-broadcast/refs/heads/main/generalsports.m3u"
          # GITHUB_REPO: "a7shk1/m3u-broadcast"
          # GITHUB_BRANCH: "main"
          # DEST_REPO_PATH: "generalsports.m3u"
          # COMMIT_MESSAGE: "chore: update Match! Football 1/2/3 from daddylive"
        run: |
          python scripts/pull_match_football_from_daddylive.py
