name: Update Premier League M3U

on:
  schedule:
    - cron: "*/5 * * * *"   # كل 5 دقائق
  workflow_dispatch:        # يدوي إذا تحب

permissions:
  contents: write

jobs:
  update-premierleague:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCE_URL: "https://raw.githubusercontent.com/pigzillaaa/daddylive/refs/heads/main/daddylive-events.m3u8"
          DEST_RAW_URL: "https://raw.githubusercontent.com/a7shk1/m3u-broadcast/refs/heads/main/premierleague.m3u"
          GITHUB_REPO: "a7shk1/m3u-broadcast"
          GITHUB_BRANCH: "main"
          DEST_REPO_PATH: "premierleague.m3u"
          COMMIT_MESSAGE: "🔄 auto-update premierleague.m3u (every 5min)"
        run: python scripts/pull_channels_and_update.py
